name: Hakyll Gh Pages

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: haskell/actions/setup@v2
      with:
        ghc-version: '8.10.7'
        cabal-version: '3.6'

    - name: Set up tailwindcss
      run: |
        npm install
        npx tailwindcss -i ./css/extra.css -o ./css/tailwind-extra.css
        npx tailwindcss -o ./css/tailwind.css

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies 
    - name: Build
      run: cabal build
    - name: Build site
      run: cabal exec site build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./_site
